consul:
  host: xxx.xxx.xxx.xxx
  port: 8500

service:
  serviceId: ken-gateway
  host: localhost
  port: 9999

check:
  http: http://xxx.xxx.xxx.xxx:9999/ping
  timeout: 5s
  interval: 5s
  deregisterCriticalServiceAfter: 20s